[package]
name = "attend_schedule_interpreter"
version = "0.1.0"
authors = ["Hampus Avekvist <hampus@avekvist.com>"]
edition = "2018"

[dependencies]
#regex = "1.1.0"
#reqwest = "0.9.6"
#scraper = "0.9.0"
#select = "0.4.2"
